# legal_tests.py

LEGAL_REFERENCES = {
    "Offer": """An offer is a definite promise to be bound on specified terms, communicated to the other party. It must be distinguished from a mere invitation to treat, a statement of willingness to negotiate, or a non-committal or conditional statement (e.g. "I might consider", "no promises").""",
    
    "Acceptance": """Acceptance occurs when the person receiving an offer agrees to it, either by a clear statement of acceptance or through their conduct. Acceptance must be unequivocal, and it must be communicated to the person who made the offer -- silence or inaction is not enough; the law does not treat a person as having accepted merely because they failed to expressly reject. Acceptance must match precisely what was offered. If the response introduces new, different, or additional terms, it is not a valid acceptance but a counter-offer, and it is then up to the original offeror to decide whether to accept that counter-offer.""",
    
    "Intention to Create Legal Relations": """Intention to create legal relations is judged objectively -- not by what the parties subjectively felt, but by what a reasonable person would consider they intended, given the circumstances in which the agreement was reached. Where parties are dealing at arm's length in a commercial context, courts generally presume they intended to create a binding legal relationship. Where an agreement is between family members or friends and has the character of a domestic or social arrangement, courts generally presume the opposite -- that no legally binding relationship was intended -- unless there is clear evidence to the contrary. A bare statement in the document asserting that the parties intend to be legally bound does not, on its own, overcome objective circumstances suggesting an informal, domestic, or social arrangement.""",
    
    "Consideration": """Consideration is the price paid for a promise -- something of value given, done, or promised by one party in exchange for the other party's promise. It does not have to be money; it can be a right, benefit, or interest given, or a detriment or loss undertaken. Courts do not weigh whether the consideration given is adequate, so long as it is real and has some value. Love, affection, or a purely voluntary gift, with nothing given in return, is not valid consideration. A promise that leaves the promisor with complete discretion over whether to perform at all -- with no genuine binding commitment -- is not real consideration. The consideration must also not be illegal or impossible to perform. An exception applies to documents properly executed as a deed: a valid deed does not require consideration to be binding, provided it is genuinely signed, sealed (or expressed to be sealed), and delivered in accordance with the applicable formalities.""",
    
    "Legal Capacity": """Legal capacity refers to a person's legal ability to enter into a binding contract. Certain categories of people have limited capacity, including: people with a mental impairment (a contract is not valid unless the person had the capacity to genuinely understand the general nature of the contract); young people under 18 years of age (minors) -- contracts with a minor for goods that are not "necessaries" (such as food, clothing, shelter, medicine, or things connected with their education or apprenticeship) are generally not binding on the minor, and contracts for credit or borrowed money are also not binding on a minor regardless of the goods involved; bankrupts (who retain general contractual capacity but face some statutory restrictions); and corporations (which have capacity to contract through persons acting with actual or apparent authority). Where a party lacks legal capacity, a contract with that party may be void or unenforceable against them.""",
    
    "Consent": """Consent to a contract must be genuine, involving free will and proper understanding by each party of what they are doing. Genuine consent can be undermined by: (a) mistake -- but only where the mistake goes to the very basis of the agreement; (b) misrepresentation or misleading conduct that induced a party to enter the contract; (c) duress -- actual or threatened harm, including economic duress (threats to a person's business or livelihood), that deprives a party of their free will to decide; (d) undue influence -- taking unfair and improper advantage of another party's weakness or vulnerability such that they did not voluntarily enter the contract. This can arise even without a formally recognised relationship (such as solicitor-client or doctor-patient) wherever one party has a position of trust, dependency, or authority over the other -- for example, where one party has taken on responsibility for managing the other's day-to-day affairs. Where such a relationship of trust and dependency exists, a presumption of undue influence arises, and it falls to the stronger party to show that the weaker party received independent advice or otherwise entered the contract free of that influence; and (e) unfair contract terms in standard form contracts. If any of these matters affected a party's consent, the contract may not be binding on that party.""",
    
    "Legality": """A contract, or a term of a contract, that involves illegal conduct may be void and unenforceable. Certain contracts are illegal at common law because they are contrary to public policy, including contracts to commit a crime, tort, or fraud; contracts to defraud the revenue (for example, deliberately misstating a transaction's true value in order to reduce tax or duty payable); contracts that prejudice public safety or the administration of justice; contracts that tend to promote corruption; and contracts in unreasonable restraint of trade. An illegally formed contract is generally void and unenforceable by either party. Where a contract that was legally formed is performed in an illegal manner, the contract itself is not necessarily void, but the party responsible for the illegal performance cannot claim remedies, though the innocent party retains its rights."""
}